stdout = ''
stderr = '''
error: expression was applied to an unexpected argument
  ┌─ tests/fail/elaboration/unexpected-argument/record-type.fathom:3:14
  │
3 │ { x : Type } x y
  │ ------------ ^ unexpected argument
  │ │             
  │ expression of type Type

'''
